# Generated by Django 3.0.8 on 2020-07-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200730_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='Grey_thumb.png', upload_to=''),
        ),
    ]
