# Generated by Django 3.0.8 on 2020-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200730_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='Grey_thumb.png', null=True, upload_to=''),
        ),
    ]
