# Generated by Django 3.0.8 on 2020-07-31 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200731_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 22, 57, 32, 795677)),
        ),
    ]
