# Generated by Django 3.0.8 on 2020-08-11 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200801_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.PositiveIntegerField(error_messages={'required': 'Please enter your bid amount.'}),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 9, 30, 16, 45259)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(error_messages={'required': 'This field cannot be empty.'}),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.PositiveIntegerField(error_messages={'required': 'This field cannot be empty.'}),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(error_messages={'required': 'This field cannot be empty.'}, max_length=100),
        ),
    ]
